### ISSUE TITLE
Having different result between CAGEexp and CAGEset in aggregateTagClusters 

### ISSUE THREAD

**Issue by arvin-cfs** [charles-plessy/CAGEr#40]
Hi Charles,

I found there are some different result  by using CAGEexp and CAGEset. The version of CAGEr is CAGEr_1.34.0. 
1. After quantilePositions,  CAGEexp has 1 position more than CAGEset in the q_0.1 and q_0.9.
2. After aggregateTagClusters, The Consensus Clusters have different number between CAGEexp and CAGEset. And the score and tpm of consensus clusters by using CAGEset have 0 value.

I compared the CAGEexp and CAGEset, Because  I imported the bam file by CAGEexp, I got the error information "first error: correctSystematicG not supported yet for CAGEexp objects". I have to set correctSystematicG = FALSE. It can import the bam file and correct G by using CAGEset. But the Consensus Clusters are different. So i am confused. Hope you can help me. 

In order to make it clear. I used the system example file to make the example.  Thank you very much.

`############## CAGEexp
library(CAGEr)
library(BSgenome.Drerio.UCSC.danRer7)
inputFiles = list.files( system.file("extdata", package = "CAGEr")
                       , "ctss$"
                       , full.names = TRUE)

ce <- CAGEexp( genomeName     = "BSgenome.Drerio.UCSC.danRer7"
             , inputFiles     = inputFiles
             , inputFilesType = "ctss"
             , sampleLabels   = sub( ".chr17.ctss", "", basename(inputFiles))
)

getCTSS(ce)

mergeSamples(ce, mergeIndex = c(3,2,4,4,1), 
                   mergedSampleLabels = c("Zf.unfertilized.egg", "Zf.high", "Zf.30p.dome", "Zf.prim6"))

plotReverseCumulatives(ce, fitInRange = c(5, 1000), onePlot = TRUE)

normalizeTagCount(ce, method = "powerLaw", fitInRange = c(5, 1000), alpha = 1.2, T = 5*10^4)

clusterCTSS( ce
                 , threshold = 1
                 , thresholdIsTpm = TRUE
                 , nrPassThreshold = 1
                 , method = "distclu"
                 , maxDist = 20
                 , removeSingletons = TRUE
                 , keepSingletonsAbove = 5)

cumulativeCTSSdistribution(ce, clusters = "tagClusters", useMulticore = T)
quantilePositions(ce, clusters = "tagClusters", qLow = 0.1, qUp = 0.9)

tagClustersGR( ce, "Zf.unfertilized.egg"
             , returnInterquantileWidth = TRUE,  qLow = 0.1, qUp = 0.9)

aggregateTagClusters(ce, tpmThreshold = 5, qLow = 0.1, qUp = 0.9, maxDist = 100)

consensusClustersGR(ce)

################ CAGEset
library(CAGEr)
library(BSgenome.Drerio.UCSC.danRer7)

myCAGEset <- new("CAGEset", genomeName = "BSgenome.Drerio.UCSC.danRer7", inputFiles = inputFiles, inputFilesType = "ctss", sampleLabels   = sub( ".chr17.ctss", "", basename(inputFiles)))

getCTSS(myCAGEset)

mergeSamples(myCAGEset, mergeIndex = c(3,2,4,4,1), 
                   mergedSampleLabels = c("Zf.unfertilized.egg", "Zf.high", "Zf.30p.dome", "Zf.prim6"))

plotReverseCumulatives(myCAGEset, fitInRange = c(5, 1000), onePlot = TRUE)

normalizeTagCount(myCAGEset, method = "powerLaw", fitInRange = c(5, 1000), alpha = 1.2, T = 5*10^4)

clusterCTSS( myCAGEset
                 , threshold = 1
                 , thresholdIsTpm = TRUE
                 , nrPassThreshold = 1
                 , method = "distclu"
                 , maxDist = 20
                 , removeSingletons = TRUE
                 , keepSingletonsAbove = 5)

cumulativeCTSSdistribution(myCAGEset, clusters = "tagClusters", useMulticore = T)
quantilePositions(myCAGEset, clusters = "tagClusters", qLow = 0.1, qUp = 0.9)

tagClustersGR( myCAGEset, "Zf.unfertilized.egg"
             , returnInterquantileWidth = TRUE,  qLow = 0.1, qUp = 0.9)

aggregateTagClusters(myCAGEset, tpmThreshold = 5, qLow = 0.1, qUp = 0.9, maxDist = 100)

consensusClustersGR(myCAGEset)
`
########################### result screen ############
![Screenshot from 2021-08-24 12-51-16](https://user-images.githubusercontent.com/11872064/130609345-7f5bace0-4b53-45ab-9fdd-1ba9143fc8a9.png)
![Screenshot from 2021-08-24 12-51-27](https://user-images.githubusercontent.com/11872064/130609346-635ab673-eaaa-45ae-844d-6135b356ef97.png)
![Screenshot from 2021-08-24 12-53-15](https://user-images.githubusercontent.com/11872064/130609347-b11ebd25-d661-4cc7-bd11-15066776076d.png)

**Comment by charles-plessy** [comment]
Hi Arvin, in the next version of CAGEr, I am dropping the `CAGEset` class entirely.  So I would like to concentrate in making sure that the `CAGEexp` class functions correctly.  If I can summarise, you are reporting two issues:

 1) Quantile positions: are they calculated correctly? The discrepancy between `CAGEset` and `CAGEexp` may be alarming. This said, it may be a bug in the `tagClustersGR` function, because for `CAGEset` it has to convert its native format to a `GRanges` object, while in the case of `CAGEexp` the information is directly stored in `GRanges`.

 2) Consensus clusters: are they calculated correctly? The discrepancy between `CAGEset` and `CAGEexp` is alarming.

Can you help me by checking if the results with the `CAGEset` class are accurate given the input data, and if you find some errors, can you open an issue per error with an explanation on which cluster or quantile position are incorrect? That would be very helpful as I have very little time for CAGEr this month.

In the meantime, I will close this issue.

Cheers,

Charles

**Comment by charles-plessy** [comment]
Hi again, regarding quantile positions, I checked the source code and I am confident that the `CAGEexp` data is correct. I have brushed up the code so that it is easier to review for third parties: https://github.com/charles-plessy/CAGEr/blob/master/R/QuantileWidthMethods.R

For the consensus clusters, please open a new issue if needed.

**Comment by charles-plessy** [comment]
Hi Arvin, after merging the replicates in CAGEr, the resulting object has no normalised counts yet, and you need to run `normalizeTagCount` again.
